POST http://localhost:8080/send
Content-Type: application/json

{
  "subject": "Subject",
  "to": "example@mail.ru",
  "text": "Finally it work!"
}
###
POST http://localhost:8080/send
Content-Type: application/json

{
  "subject": "Best Version",
  "to": "example@gmail.com",
  "text": "Finally found it!"
}